Ejercicio1: Ejercicio1/ mefmods.py
	make -C Ejercicio1

clean: 
	find -iname __pycache__ | xargs rm -r
	find -iname .\*swp \
	  -o -iname \*.dat \
	  -o -iname \*.png\
	  -o -iname \*.jpg\
	  -o -iname \*.pdf\
	  | xargs rm

.PHONY: Ejercicio1
