# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kY5o535o_hsPubaYB5q2AVymQmrYWEhc
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-np.pi,np.pi,100)
plt.plot(x,np.sin(x))

import Ejercicio1.py

./Ejercicio1.py

!python Ejercicio1.py

plt.show()

ls



from google.colab import drive
drive.mount('/content/drive')